[package]
name = "vlmcs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Async and blocking KMS V4/V5/V6 clients"

[features]
default = ["async", "blocking", "cli"]
std = ["dep:getrandom", "dep:thiserror"]
async = ["std", "dep:tokio"]
blocking = ["std"]
cli = ["async", "dep:clap", "tokio/macros", "tokio/rt"]

[[bin]]
name = "vlmcs"
path = "src/main.rs"
required-features = ["cli"]

[[test]]
name = "client"
required-features = ["async", "cli"]

[dependencies]
getrandom = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
vlmcsd-protocol.workspace = true
tokio = { workspace = true, optional = true, features = ["net", "io-util", "time"] }
clap = { workspace = true, optional = true }

[lints]
workspace = true

[dev-dependencies]
vlmcsd = { version = "0.1.0", path = "../vlmcsd", default-features = false, features = ["async", "blocking"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time", "process"] }

[[test]]
name = "blocking"
required-features = ["blocking"]
